name: Ubuntu Client

on:
  push:
    branches:
      - main2
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ arm64, amd64 ]

    steps:
      - name: Check architecture
        run: |
          echo "Running on $(uname -m)"

      - name: Set up QEMU (for ARM64 emulation)
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Check architecture 2
        run: |
          echo "Running on $(uname -m)"

      - uses: actions/checkout@v2

      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 5.4.0
      - run: bazel version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential autoconf libtool pkg-config

      - name: Build
        run: |
          cd client
          bazel build //:client
